
import static java.awt.Color.blue;
import static java.awt.Color.magenta;
import static java.awt.Color.red;
import javax.swing.JButton;
import javax.swing.JFrame;
import javax.swing.JOptionPane;

/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */

/**
 *
 * @author Avinash Gupta
 */
public class TikTacToeFrame extends javax.swing.JFrame {

    /**
     * Creates new form TikTacToeFrame
     */
    
    private String turn = "X";
    private int xCount = 0;
    private int oCount = 0;
    
    public TikTacToeFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtButton1 = new javax.swing.JButton();
        txtButton7 = new javax.swing.JButton();
        txtButton4 = new javax.swing.JButton();
        txtButton2 = new javax.swing.JButton();
        txtButton3 = new javax.swing.JButton();
        txtButton6 = new javax.swing.JButton();
        txtButton5 = new javax.swing.JButton();
        txtButton8 = new javax.swing.JButton();
        txtButton9 = new javax.swing.JButton();
        reset = new javax.swing.JButton();
        exit = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        xScore = new javax.swing.JLabel();
        oScore = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("TiC- TaK-ToE");

        jPanel1.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.setFont(new java.awt.Font("Arial", 1, 14)); // NOI18N

        jLabel1.setFont(new java.awt.Font("Sitka Subheading", 1, 48)); // NOI18N
        jLabel1.setText("TiC taC TOe Game");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(189, 189, 189)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addContainerGap(15, Short.MAX_VALUE)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 52, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap())
        );

        txtButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtButton1ActionPerformed(evt);
            }
        });

        txtButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtButton7ActionPerformed(evt);
            }
        });

        txtButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtButton4ActionPerformed(evt);
            }
        });

        txtButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtButton2ActionPerformed(evt);
            }
        });

        txtButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtButton3ActionPerformed(evt);
            }
        });

        txtButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtButton6ActionPerformed(evt);
            }
        });

        txtButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtButton5ActionPerformed(evt);
            }
        });

        txtButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtButton8ActionPerformed(evt);
            }
        });

        txtButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtButton9ActionPerformed(evt);
            }
        });

        reset.setBackground(new java.awt.Color(0, 204, 204));
        reset.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        reset.setText("RESET");
        reset.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetActionPerformed(evt);
            }
        });

        exit.setBackground(new java.awt.Color(255, 0, 0));
        exit.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        exit.setText("EXIT");
        exit.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                exitActionPerformed(evt);
            }
        });

        jPanel2.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel2.setText("PlayerX:");

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N
        jLabel3.setText("PlayerO:");

        xScore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        oScore.setFont(new java.awt.Font("Segoe UI", 1, 14)); // NOI18N

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addGap(32, 32, 32)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(oScore, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xScore, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(33, 33, 33)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(xScore, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(oScore, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(layout.createSequentialGroup()
                .addGap(56, 56, 56)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(txtButton4, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtButton7, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(54, 54, 54)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(53, 53, 53)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtButton9, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtButton6, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 82, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(51, 51, 51)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(reset, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(27, 27, 27)
                        .addComponent(exit, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(42, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(31, 31, 31)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtButton3, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 24, Short.MAX_VALUE)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(txtButton4, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(txtButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(txtButton5, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(txtButton7, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(txtButton8, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(txtButton9, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 62, Short.MAX_VALUE)
                    .addComponent(reset, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(exit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(35, 35, 35))
        );

        txtButton1.getAccessibleContext().setAccessibleDescription("");

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void exitActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_exitActionPerformed
        JFrame frame = new JFrame("Exit");
        
        if(JOptionPane.showConfirmDialog(frame,"Confirm if you want to Exit",
                "Tic TAC TOE",JOptionPane.YES_NO_OPTION)== JOptionPane.YES_NO_OPTION){
            System.exit(0);
        }
        
    }//GEN-LAST:event_exitActionPerformed

    private void txtButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtButton1ActionPerformed
          if(txtButton1.getBackground().getRGB() == -2696737){
                backgroundColor(txtButton1);
                choosePlayer();
                chooseWinner(txtButton1.getBackground().getRGB(),0);
            }

    }//GEN-LAST:event_txtButton1ActionPerformed

    private void txtButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtButton2ActionPerformed
       if(txtButton2.getBackground().getRGB() == -2696737){
        backgroundColor(txtButton2);
        choosePlayer();
        chooseWinner(txtButton2.getBackground().getRGB(),1);
       }
    }//GEN-LAST:event_txtButton2ActionPerformed

    private void txtButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtButton3ActionPerformed
        if(txtButton3.getBackground().getRGB() == -2696737){
            backgroundColor(txtButton3);
            choosePlayer();
            chooseWinner(txtButton3.getBackground().getRGB(),2);
        }
    }//GEN-LAST:event_txtButton3ActionPerformed

    private void txtButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtButton4ActionPerformed
        if(txtButton4.getBackground().getRGB() == -2696737){
            
            backgroundColor(txtButton4);
            System.out.println(txtButton4.getBackground().getRGB());
            choosePlayer();
            chooseWinner(txtButton4.getBackground().getRGB(),3);
        }
    }//GEN-LAST:event_txtButton4ActionPerformed

    private void txtButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtButton5ActionPerformed
        if(txtButton5.getBackground().getRGB() == -2696737){
            backgroundColor(txtButton5);
            choosePlayer();
            chooseWinner(txtButton5.getBackground().getRGB(),4);
        }
    }//GEN-LAST:event_txtButton5ActionPerformed

    private void txtButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtButton6ActionPerformed
        if(txtButton6.getBackground().getRGB() == -2696737){
            backgroundColor(txtButton6);
            choosePlayer();
            chooseWinner(txtButton6.getBackground().getRGB(),5);
        }
    }//GEN-LAST:event_txtButton6ActionPerformed

    private void txtButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtButton7ActionPerformed
        if(txtButton7.getBackground().getRGB() == -2696737){ 
            backgroundColor(txtButton7);
            choosePlayer();
            chooseWinner(txtButton7.getBackground().getRGB(),6);
        }
    }//GEN-LAST:event_txtButton7ActionPerformed

    private void txtButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtButton8ActionPerformed
         if(txtButton8.getBackground().getRGB() == -2696737){ 
            backgroundColor(txtButton8);
            choosePlayer();
            chooseWinner(txtButton8.getBackground().getRGB(),7);
         }
    }//GEN-LAST:event_txtButton8ActionPerformed

    private void txtButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtButton9ActionPerformed
        if(txtButton9.getBackground().getRGB() == -2696737){ 
            backgroundColor(txtButton9);
            choosePlayer();
            chooseWinner(txtButton9.getBackground().getRGB(),8);
        } 
    }//GEN-LAST:event_txtButton9ActionPerformed

    private void resetActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetActionPerformed
        txtButton1.setBackground(new JButton().getBackground());
        txtButton2.setBackground(new JButton().getBackground());
        txtButton3.setBackground(new JButton().getBackground());
        txtButton4.setBackground(new JButton().getBackground());
        txtButton5.setBackground(new JButton().getBackground());
        txtButton6.setBackground(new JButton().getBackground());
        txtButton7.setBackground(new JButton().getBackground());
        txtButton8.setBackground(new JButton().getBackground());
        txtButton9.setBackground(new JButton().getBackground());
    }//GEN-LAST:event_resetActionPerformed

    public void chooseWinner(int color,int index){
        
        if(color ==  -269737) return;
        
        int colorValue[][] = new int[3][3]; 
        colorValue[0][0] = txtButton1.getBackground().getRGB();
        colorValue[0][1] = txtButton2.getBackground().getRGB();
        colorValue[0][2] = txtButton3.getBackground().getRGB();
        colorValue[1][0] = txtButton4.getBackground().getRGB(); 
        colorValue[1][1] = txtButton5.getBackground().getRGB();
        colorValue[1][2] = txtButton6.getBackground().getRGB();
        colorValue[2][0] = txtButton7.getBackground().getRGB();
        colorValue[2][1] = txtButton8.getBackground().getRGB();
        colorValue[2][2] = txtButton9.getBackground().getRGB();
        
        boolean flagH = true;
        //same row check
        for(int i=0;i<3;i++){
            if(colorValue[index/colorValue[0].length][i] != color){
                flagH = false;
                break;
            }
        }
        boolean flagV = true;
        for(int i=0;i<3;i++){
            if(colorValue[i][index%3] != color){
                flagV = false;
                break;
            }
        }
        
        boolean flagDL = true;
        for(int i=0;i<3;i++){
            if(colorValue[i][i] != color){
                flagDL = false;
                break;
            }
        }
        
        boolean flagDR = true;
        for(int i=0;i<3;i++){
            if(colorValue[i][3-i-1] != color){
                flagDR = false;
                break;
            }
        }

        if(flagH || flagV || flagDL || flagDR){
            System.out.println(flagV);
           if(color == -65536 ){
                JOptionPane.showMessageDialog(this,"Player X wins","Tic Tac Toe",JOptionPane.INFORMATION_MESSAGE);
                xCount++;
                
            }else if(color == -16776961){
                JOptionPane.showMessageDialog(this,"Player O wins","Tic Tac Toe",JOptionPane.INFORMATION_MESSAGE);
                oCount++;
            }
            setScore();
        }
        
//        if((b1 == - && b2 == b3) || (b7 == b8 && b8 == b9) || (b4 == b5 && b5 == b6) 
//           || (b1 == b5 && b5 == b9) || (b3 == b5 && b5 == b7) 
//           || (b1 == b4 && b4 == b7) ||(b2 == b5 && b5 == b9) || (b3 == b6 && b6 == b8)) {
//           if(color == -65536 ){
//                JOptionPane.showMessageDialog(this,"Player X wins","Tic Tac Toe",JOptionPane.INFORMATION_MESSAGE);
//                xCount++;
//                
//            }else{
//                JOptionPane.showMessageDialog(this,"Player O wins","Tic Tac Toe",JOptionPane.INFORMATION_MESSAGE);
//                oCount++;
//            }
//            setScore();
//        } 
    }
    
    private  void setScore(){
        xScore.setText(String.valueOf(xCount));
        oScore.setText(String.valueOf(oCount));
    }
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(TikTacToeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(TikTacToeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(TikTacToeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(TikTacToeFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new TikTacToeFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton exit;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JLabel oScore;
    private javax.swing.JButton reset;
    private javax.swing.JButton txtButton1;
    private javax.swing.JButton txtButton2;
    private javax.swing.JButton txtButton3;
    private javax.swing.JButton txtButton4;
    private javax.swing.JButton txtButton5;
    private javax.swing.JButton txtButton6;
    private javax.swing.JButton txtButton7;
    private javax.swing.JButton txtButton8;
    private javax.swing.JButton txtButton9;
    private javax.swing.JLabel xScore;
    // End of variables declaration//GEN-END:variables

    public void choosePlayer() {
        if(turn.equalsIgnoreCase("X")){
            turn = "O";
        }else{
            turn = "X";
        }
    }

    public void backgroundColor(JButton txtButton) {
        if(turn.equalsIgnoreCase("X")){
            txtButton.setBackground(red);
        }else{
            txtButton.setBackground(blue);
        } 
    }
}
